# Setup
title:               State of things
tagline:             'Updates and stuff'
description:         'A place for all updates, important or not'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              davion
  url:               ''
  email:             nomail@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0
google_analytics_id: #UA-XXXX-Y
